// LOCALHOST
//Tested in Thunder...

### Get Hello World
GET http://localhost:8080


### Get professional information for Tiffany Voorhees from the database (the only record in the database)
GET http://localhost:8080/professional


### Get all contacts
GET http://localhost:8080/contacts


### Get contact by id (Scott)
GET http://localhost:8080/contacts/66eb26516073ae1d8207a57b

### Create a new contact
POST http://localhost:8080/contacts HTTP/1.1
content-type: application/json

{
"firstName": "Vaughn",
"lastName": "Voorhees",
"email": "vaughn@gmail.com",
"favoriteColor": "Black",
"birthday": "2018-02-06T00:00:00.000Z"
}

### Update a contact
PUT http://localhost:8080/contacts/66eb26516073ae1d8207a57b HTTP/1.1
content-type: application/json

{
  "firstName": "Scott",
  "lastName": "Voorhees",
  "email": "scott@gmail.com",
  "favoriteColor": "Black",
  "birthday": "1986-02-06T00:00:00.000Z"
}

### Delete a contact 
DELETE http://localhost:8080/contacts/66fd799ad517c45b3d48a3f4 HTTP/1.1



//PRODUCTION ON RENDER
### Get Hello World
GET https://cse341-web-services-bd0o.onrender.com/


### Get professional information for Tiffany Voorhees from the database (the only record in the database)
GET https://cse341-web-services-bd0o.onrender.com/professional


### Get all contacts
GET https://cse341-web-services-bd0o.onrender.com/contacts


### Get contact by id
GET https://cse341-web-services-bd0o.onrender.com/contacts/66eb26516073ae1d8207a57b

### Create a new contact
POST https://cse341-web-services-bd0o.onrender.com/contacts HTTP/1.1
content-type: application/json

{
"firstName": "Vaughn",
"lastName": "Voorhees",
"email": "vaughn@gmail.com",
"favoriteColor": "Black",
"birthday": "2018-02-06T00:00:00.000Z"
}

### Update a contact
PUT https://cse341-web-services-bd0o.onrender.com/contacts/66eb26516073ae1d8207a57b HTTP/1.1
content-type: application/json

{
  "firstName": "Scott",
  "lastName": "Voorhees",
  "email": "scott@gmail.com",
  "favoriteColor": "Black",
  "birthday": "1986-02-06T00:00:00.000Z"
}

### Delete a contact 
DELETE https://cse341-web-services-bd0o.onrender.com/contacts/66f4840c2a223f5d3f190c7f HTTP/1.1

